### ISSUE TITLE
Planks Frames cant walk through door frame, but can after upgrading

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#16]

**Comment by nbaggett** [comment]
@westonleavitt This is an issue with the 3d model for the planks mesh. Since its combined, I can't edit it in blender to fix this. Here you can see the log doorway and the planks doorway overlaid over one another. The planks frame is not large enough to accommodate a player.
![image](https://user-images.githubusercontent.com/43483627/207732644-f966ea50-400f-4f07-9923-ee7752a3d619.png)

**Comment by westonleavitt** [comment]
okay I'll fix the mesh. can you just adjust the colliders to clip a little bit for now

**Comment by nbaggett** [comment]
> @nbaggett okay I'll fix the mesh. can you just adjust the colliders to clip a little bit for now

It's using a mesh collider but I can make a couple box colliders for now.
