### ISSUE TITLE
player controller becomes locked when...

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#185]
1. open console
2. click npc
3. spawn an npc
4. close console.

**Comment by tykennington** [comment]
commit b6da1f8.

Problem came up because I disabled movement when UI controls, like input fields, are active, and that apparently included buttons, oops. To avoid this in the future, it's probably best to just deselect UI when we're done, since that could cause unexpected behavior anyway (like navigating an invisible menu and pressing buttons again when you're just trying to move)
