### ISSUE TITLE
Add Current velocity of throwing player to the velocity of a throwable

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#327]
I think if the player is moving we should add the velocity of the player to the velocity of the throwable. Otherwise chasing something and throwing at the same time tends to result with the throwable not being seen because the player moves faster the the projectile. you can even throw some objects and then get hit in the head from behind with the projectile if your move speed is greater than the throwables. adding the players velocity would be physics realistic.

**Comment by nbaggett** [comment]
@westonleavitt Good catch! I'll implement this asap, but I also think it might be worth slowing the player movement speed when charging a throwable, charging a spell, drawing a bow, reloading, etc... to even out melee vs ranged combat. At the moment ranged players have a massive advantage since there are no movement penaltys and you can sprint omni-directionally, so you can just backpedal indefinitely and the melee attacker can never get in range.

**Comment by westonleavitt** [comment]
agreed. will add seperate task

**Comment by nbaggett** [comment]
implemented a bit ago but i forgot to close this
