### ISSUE TITLE
Picking up deployable gets rid of housed resources

### ISSUE THREAD

**Issue by lukewoodruff** [westonleavitt/TheOccultBugTracker#441]
### Contact Details

Luke

### What happened?

Example: You pick up a candlestand with oil in it, and the oil dissapears.

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

Pick up deployable with resource in it.

**Comment by tykennington** [comment]
Commit 22a5edf

Like with input slots and grid items, it now disallowed picking up an item with fuel. Except I made exceptions for water barrels and animal enclosures:

- It's not easy to remove water from barrels, because there is no "Water" item. I figured it would be a bad idea to make it impossible to pick up a barrel if you don't have a hundred buckets you can fill.
- Animal enclosures accept multiple types of food as fuel, and it all gets converted to a single integer. Food cannot be removed from an enclosure because it is unknown which kind of food to remove.
