### ISSUE TITLE
bird collider takes all hits within huge collider radius after dead.

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#47]
Kill a bird in the scene and the collider will then absorb any raycast type attacks because of its collider remaining active -- it also never despawns?

![image](https://user-images.githubusercontent.com/99469587/211712103-7fae8532-9f07-487f-93f0-bacecd7d7cb3.png)

**Comment by nbaggett** [comment]
@westonleavitt Fixed the despawn issue and now disable the trigger on death too. However, the bird is receiving hits for this massive collider because that's the trigger for the NetworkObservee class. The bird still takes damage from too far away when alive due to this setup.
![image](https://user-images.githubusercontent.com/43483627/211861003-80c885fd-5e69-4d48-a984-47f0e4340734.png)

**Comment by westonleavitt** [comment]
okay cool. this collider is gone now so shouldnt be an issue
