### ISSUE TITLE
Cant connect normal sized walls to quarter walls

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#6]

**Comment by nbaggett** [comment]
This is intentional as the quarter walls are really closer to 1/3 walls. In order to prevent players from abusing this to offset floor tiles from half or full increments, I've prevented players from stacking walls on top of quarter walls.

Height difference visualized below:

![image](https://user-images.githubusercontent.com/43483627/207659437-604fa54d-e198-487a-8955-fa5bbc5945f4.png)

Rust also prevents players from connecting walls to their low height walls. I think renaming the wall to low wall might be better as its not actually a quarter.
