### ISSUE TITLE
birds never despawn after killing them. they are also unlootable

### ISSUE THREAD

**Issue by westonleavitt** [westonleavitt/TheOccultBugTracker#75]
### What happened?

birds never despawn after killing them. they are also unlootable

### Did your game crash?

- [ ] Yes, my game crashed.

### Steps To Reproduce

birds never despawn after killing them. they are also unlootable

### Screen Recording or Screenshot

birds never despawn after killing them. they are also unlootable

**Comment by nbaggett** [comment]
Birds despawn, but I reduced the time it takes so they despawn after 2 minutes instead of 6 minutes.

Made birds lootable as well. Birds will despawn if they are looted.

@westonleavitt birds still have a large trigger from the network observee allowing them to be hit when they shouldn't. I don't know the best way to work around this, we likely need the network observee on a different object so it can be on a layer that ignores raycasts.
