### ISSUE TITLE
[Thread] General playtest feedback 2/9/2023

### ISSUE THREAD

**Issue by nbaggett** [westonleavitt/TheOccultBugTracker#87]
## Overview
I know we're still early for a lot of polish elements, but I wanted to get my thoughts down in here before I forget. Please comment any polish things you noticed in here as well. I think game feel is critical for retaining players early, and nailing a lot of our polish is very important. A lot of the feedback for Dark and Darker have been that the game feel is amazing, but a lot of the other game elements in it are lackluster. Good game feel can really make an experience. 

- I think the depth of field post process is a bit too strong, I can't see very far at all in the game. I think it should be toned down or disabled.
- I like the idea of music for different areas, but I don't think it matches the monuments. I think a more general ambient loop would fit better for the monuments, with music for safe zones. 
- I like our inventory UI, but I don't like having to hold alt while navigating it. I would like the option when we get to a settings menu to have it be a toggle (like on tab or something)
- XP in the chat clutters other messages, maybe we have different UI for xp, but put important events in the chat?
- Holding alt with the build hammer registers clicks as building server RPCS, making it tricky when trying to build and accidentally building parts. I should disable building clicks while any menu is open.

**Comment by westonleavitt** [comment]
Yeah I agree. I think alot of things are almost there and a few bits of polish will go a long way. A few more polish things I was thinking about for the next few weeks:

- Terrain textures need to be scaled down
- Night time is too long/too dark
- Player Local/Multiplayer/IK/Combat/Feedback in general for sure needs some work
- terrain hole painting needs to be implemented in the generation step so that it doesnt have to be done manually
- it would be helpful to add some commands for in game testing (teleport to where you are looking for example)

**Comment by nbaggett** [comment]
More commands is a must! I need to implement commands to spawn AI as well. Also, I think I should make an item debug menu that loads all the possible items so we can more easily test them. I’ll put some more commands in next week.
